import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/app/navbar'
import Footer from '@/app/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cet',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
        <Navbar/>
        <div className="flex mt-10">

          <div className="w-3/4 bg-gray-300 p-8">
            <div className='bg-white p-8'>

            {children}  
            Columna Izquierda
            </div>
          </div>
          <div className="w-1/4 bg-gray-100 p-8">
            <div className='text-center justify-center items-center '>
              <h1 className="font-montserrat text-3xl font-semibold tracking-wide">Calendario Academico</h1>
              <br></br>
              <iframe src="https://drive.google.com/file/d/1PS0G48ZG4MFID6faloXydyOg7kuemQR8/preview" width="280" height="480" allow="autoplay" className='rounded-lg'></iframe>
            </div>
            <div>
              <h1 className="font-montserrat text-3xl font-semibold tracking-wide py-2">Autoridades</h1>
            </div>
            <div>
              
            </div>
          </div>
        </div>
        <Footer/>
      </body>
        
    </html>
  )
}
